### ISSUE TITLE
Deactivate rule when english sentence given

### ISSUE THREAD

**Issue by uetchy** [azu/textlint-rule-spellcheck-tech-word#4]
Because they look proper english words as misspellings.

```
> textlint content/*.md content/post/*.md -f pretty-error
spellcheck-tech-word:  blog =>  ブログ
/home/travis/build/randompaper/randompaper.co/content/post/2015-07-05-hugo-paper.md:8:18
                         v
    7. 
    8. When I created my blog, there are no well simplified [Hugo](http://gohugo.io) theme around the world. I need to a theme that just don't interupt reading experience. [Hugo Paper](https://github.com/uetchy/hugo-paper) is made for that.
    9. 
                         ^
spellcheck-tech-word:  blog =>  ブログ
/home/travis/build/randompaper/randompaper.co/content/post/2015-07-05-hugo-paper.md:10:24
                               v
     9. 
    10. # How to integrate your blog
    11. 
```

**Comment by azu** [comment]
We have three options.
1. Add feature that detect language to textlint.
2. Split config into `en.textlintrc` and `ja.textlintrc`. use `textlint -c en.textlintrc`
3. Use [textlint-rule-prh](https://github.com/azu/textlint-rule-prh) with [technical-word-rules](https://github.com/azu/technical-word-rules)'s dict instead of [textlint-rule-spellcheck-tech-word](https://github.com/azu/textlint-rule-spellcheck-tech-word).

3 mean that `blog =>  ブログ` is defeind in [web+db.yml](https://github.com/azu/technical-word-rules/blob/master/dict/web%2Bdb.yml).
You can ignore [web+db.yml](https://github.com/azu/technical-word-rules/blob/master/dict/web%2Bdb.yml) and load other from [technical-word-rules](https://github.com/azu/technical-word-rules).

e.g.) [reveal.js のHTMLのスライドL内のマークダウンのJavaScriptにESLintをテキストにtextlintをVimのmakeでかける方法 - Qiita](http://qiita.com/sifue/items/58da41e8b3ee4f2c54af)

**Comment by uetchy** [comment]
Thanks for response! I'll do work-around to use other rules.
However, 1st option which adds language detection support into textlint seems ideal for us.
I'd like to use textlint without concerning about which language my articles use and which plugins/rules are capable with that.

**Comment by uetchy** [comment]
One possible option is to put `{language: 'ja'}`-stuff into textlint plugins/rules.
This is better than another option because this guarantee the backward compatibility.
if you want to limit languages your plugins use, you just put this config to someplace right.

Another option is let textlint detect languages which plugins can handle by looking their name (e.g. `textlint-rule-somewhat-ja` => capable of handling Japanese)

What do you think? @azu

**Comment by uetchy** [comment]
I did quick research and [guessLanguage.js](https://github.com/richtr/guessLanguage.js/) looks good for detecting natural languages.

**Comment by azu** [comment]
Language detection cause double traversing.
I will avoid double traversing.
1. parse text 
2. traverse for detecting lang
3. traverse for appling each rule.

> Split config into en.textlintrc and ja.textlintrc. use textlint -c en.textlintrc

My recommened way is splitting config even now.
Feel free to file issue to textlint repository :)

**Comment by uetchy** [comment]
I got it 👍
Anyway, I'll send a issue about language detection to textlint repo. Thanks!
